### ISSUE TITLE
the new datapacks breaks things up

### ISSUE THREAD

**Issue by YontiLevin** [OpenBudget/open-budget-search-api#8] opened 2017-05-08 17:32 UTC
error returned from line 91 of elastic.py
something to do with the parsing of the datapack to sources

**Comment by OriHoch** [comment] 2017-05-09 08:11
@YontiLevin I'm trying to familiarize with the project, so it would be really helpful for me if you could provide some context like - where you see this error / reproduction steps / links to relevant docs
thanks

**Comment by YontiLevin** [comment] 2017-05-09 08:19
adam fixed it partly yesterday.
if you check out the new search here:
http://next.obudget.org/app/search/
you will see that it fail
i traced the failure to line 91 of elastic.py
now i checked adam's patch and it is working locally.
so i think we can close it for the moment

**Comment by OriHoch** [comment] 2017-05-09 08:24
cool, thanks, just to clarify I understood correctly -

### reproduction steps
* goto http://next.obudget.org/app/search/
* open network tab, look for the following network request:
* http://next.obudget.org/search/changes,exemption,budget,procurement,entities,supports/%D7%97%D7%99%D7%A0%D7%95%D7%9A/1992-01-01/2019-01-01/10/0
* look at the response

#### expected
* valid response

#### actual
```
{
message: "not a real type changes"
}
```

**Comment by akariv** [comment] 2017-05-09 08:28
Yep, since we've moved ES to work with the datapackages (and not the old obudget data) we've lost a few data sources (that weren't yet ported to the new pipelines framework).
This will be fixed gradually while we work on the pipeline implementation. Budget is nearly done and will be added really soon. Procurement and exemption as well.
So - for now you should just query on `entities`, or we could simply add an `all` option to the API to query on all types.

**Comment by YontiLevin** [comment] 2017-05-09 08:29
i will push the code with only entities later

**Closed** 2017-05-15 19:45 UTC
